# Generated by Django 6.0.2 on 2026-02-18 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_number', models.CharField(max_length=50, unique=True, verbose_name='Aircraft Code')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('passenger_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Passenger Capacity')),
                ('range_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Range (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('inactive', 'Inactive')], default='active', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'db_table': 'aircraft',
                'ordering': ['code_number'],
                'indexes': [models.Index(fields=['code_number'], name='idx_aircraft_code'), models.Index(fields=['status'], name='idx_aircraft_status')],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='Flight Number')),
                ('departure_point', models.CharField(max_length=100, verbose_name='Departure Point')),
                ('arrival_point', models.CharField(max_length=100, verbose_name='Arrival Point')),
                ('flight_date', models.DateField(verbose_name='Flight Date')),
                ('flight_time', models.TimeField(verbose_name='Flight Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flights', to='flights.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flights',
                'ordering': ['-flight_date', '-flight_time'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_number', models.CharField(max_length=50, unique=True, verbose_name='Passenger Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'passengers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['passenger_number'], name='idx_passenger_number'), models.Index(fields=['last_name', 'first_name'], name='idx_passenger_name')],
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seat Number')),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('boarded', 'Boarded'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=50, verbose_name='Booking Status')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.passenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name': 'Flight Booking',
                'verbose_name_plural': 'Flight Bookings',
                'db_table': 'flight_bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='PassengerAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing'), ('other', 'Other')], max_length=20, verbose_name='Address Type')),
                ('address_line', models.TextField(verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='flights.passenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name': 'Passenger Address',
                'verbose_name_plural': 'Passenger Addresses',
                'db_table': 'passenger_addresses',
            },
        ),
        migrations.CreateModel(
            name='PassengerPhone',
            fields=[
                ('phone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_type', models.CharField(choices=[('home', 'Home'), ('mobile', 'Mobile'), ('work', 'Work')], max_length=20, verbose_name='Phone Type')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='flights.passenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name': 'Passenger Phone',
                'verbose_name_plural': 'Passenger Phones',
                'db_table': 'passenger_phones',
            },
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='idx_flight_number'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_date'], name='idx_flight_date'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['aircraft'], name='idx_flight_aircraft'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['flight'], name='idx_booking_flight'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['passenger'], name='idx_booking_passenger'),
        ),
        migrations.AlterUniqueTogether(
            name='flightbooking',
            unique_together={('flight', 'passenger'), ('flight', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='passengeraddress',
            index=models.Index(fields=['passenger'], name='idx_passenger_address_passenger'),
        ),
        migrations.AddIndex(
            model_name='passengeraddress',
            index=models.Index(fields=['address_type'], name='idx_passenger_address_type'),
        ),
        migrations.AddIndex(
            model_name='passengerphone',
            index=models.Index(fields=['passenger'], name='idx_passenger_phone_passenger'),
        ),
        migrations.AddIndex(
            model_name='passengerphone',
            index=models.Index(fields=['phone_type'], name='idx_passenger_phone_type'),
        ),
        migrations.AlterUniqueTogether(
            name='passengerphone',
            unique_together={('passenger', 'phone_type')},
        ),
    ]
