# Generated by Django 6.0.2 on 2026-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passengeraddress',
            new_name='idx_pass_addr_pass',
            old_name='idx_passenger_address_passenger',
        ),
        migrations.RenameIndex(
            model_name='passengeraddress',
            new_name='idx_pass_addr_type',
            old_name='idx_passenger_address_type',
        ),
        migrations.RenameIndex(
            model_name='passengerphone',
            new_name='idx_pass_phone_pass',
            old_name='idx_passenger_phone_passenger',
        ),
        migrations.RenameIndex(
            model_name='passengerphone',
            new_name='idx_pass_phone_type',
            old_name='idx_passenger_phone_type',
        ),
    ]
