# Generated by Django 6.0.2 on 2026-02-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_flight_update_with_airports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['airport_name'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_type',
            field=models.CharField(blank=True, choices=[('large_airport', 'Large Airport'), ('medium_airport', 'Medium Airport'), ('small_airport', 'Small Airport'), ('heliport', 'Heliport'), ('seaplane_base', 'Seaplane Base'), ('balloonport', 'Balloonport'), ('closed', 'Closed')], max_length=50, null=True, verbose_name='Airport Type'),
        ),
        migrations.AddField(
            model_name='airport',
            name='continent',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Continent'),
        ),
        migrations.AddField(
            model_name='airport',
            name='elevation_ft',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elevation (ft)'),
        ),
        migrations.AddField(
            model_name='airport',
            name='gps_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='GPS Code'),
        ),
        migrations.AddField(
            model_name='airport',
            name='ident',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OurAirports Identifier'),
        ),
        migrations.AddField(
            model_name='airport',
            name='iso_country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='ISO Country Code'),
        ),
        migrations.AddField(
            model_name='airport',
            name='iso_region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO Region Code'),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='airport',
            name='local_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Local Code'),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='airport',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='airport',
            name='scheduled_service',
            field=models.BooleanField(default=False, verbose_name='Scheduled Service'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='IATA Code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO Code'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['ident'], name='idx_airport_ident'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['airport_type'], name='idx_airport_type'),
        ),
    ]
